let fs = require('fs');
const MULTIFOCAL_LENS_TYPE_ID = 7;
const detailedResponse = {
    total: 3,
    items: [
        {
            id: 9674,
            url: 'annex.html',
            name: 'Annex',
            sku: 'annex-window',
            attributeSetId: 30,
            typeId: 'glasseswindow',
            brand: {
                image: '/brand/1/Ottoto_1_image.png',
                id: 219,
                label: 'Ottoto',
                popular: 0,
                url: '/ottoto',
                imageHeight: 20,
                categoryId: 71,
            },
            children: [
                {
                    color: {
                        src: '/catalog_filter_color/1/19.jpg',
                        id: '19',
                        label: 'Black',
                    },
                    isEligibleForRx: true,
                    glassesTypeIds: [225, 227, 226],
                    description:
                        'The Ottoto Annex is a stylish lightweight frame crafted from stainless steel. Sporting sleek arms and a simple design, the Annex is a sincerely reliable look.',
                    finalPrice: 53.0,
                    videos: [],
                    media: {
                        '360rotation': {
                            src: '/catalog_product_view_4086/1/311948_360.jpg',
                            qty: 20,
                            value_id: '899',
                            entity_id: '4086',
                            first: 20,
                        },
                        side: {
                            file: '/3/1/31-m1948_s.jpg',
                            src: '/catalog_product/1/31-m1948_s.jpg',
                            value_id: 194647,
                            position: 3,
                            entity_id: 4086,
                        },
                        '180rotation': {
                            src: '/catalog_product_view_4086/1/31m1948_strip.jpg',
                            qty: 5,
                            value_id: '34243',
                            entity_id: '4086',
                            first: 3,
                        },
                        '180men': {
                            src: '/catalog_product_view_4086/1/311948_m.jpg',
                            qty: 5,
                            value_id: '2161',
                            entity_id: '4086',
                            first: 3,
                        },
                        angle: {
                            file: '/3/1/31-m1948-u.jpg',
                            src: '/catalog_product/1/31-m1948-u.jpg',
                            value_id: 194648,
                            position: 1,
                            entity_id: 4086,
                        },
                        front: {
                            file: '/3/1/31-m1948_f.jpg',
                            src: '/catalog_product/1/31-m1948_f.jpg',
                            value_id: 194646,
                            position: 2,
                            entity_id: 4086,
                        },
                    },
                    type: 'eyeglasses',
                    templateId: 1,
                    isKids: false,
                    customProductBadge: [],
                    price: 89.0,
                    defaultTintSku: '',
                    id: 4086,
                    lensFeatures: [],
                    sku: '31-M1948',
                    stock: {
                        qty: 2124,
                        status: 'in_stock',
                    },
                    relatedProductSku: '',
                    brand: {
                        image: '/brand/1/Ottoto_1_image.png',
                        id: 219,
                        label: 'Ottoto',
                        popular: 0,
                        url: '/ottoto',
                        imageHeight: 20,
                        categoryId: 71,
                    },
                    lensTypeIds: [7, 6, 10],
                    coupon: {
                        code: 'LENSES25',
                        price: 53.0,
                    },
                    isDsco: false,
                    genders: ['Men'],
                    shortDescription:
                        'The Ottoto Annex is a stylish lightweight frame crafted from stainless steel. Sporting sleek arms and a simple design, the Annex is a sincerely reliable look.\r\n',
                    url: 'black-large/annex/31-m1948.html',
                    defaultDarknessSku: '',
                    wizardId: '1',
                    meta: {
                        disable_http_code: 404,
                        description:
                            'The Ottoto Annex is a stylish lightweight frame crafted from stainless steel. Sporting sleek arms and a simple design, the Annex is a sincerely reliable look.\r\n',
                        title: 'Ottoto Annex Black Prescription Eyeglasses',
                        keyword:
                            'Glasses, Eyeglasses, Eyewear, Eyeglass, Eye glasses, Eye glass, Prescription glasses, Glasses frame, Eye wear, Bifocals, Eyeglass frame, Eyeglasses frames, Prescription eyeglasses, Buy glasses, Sunglasses\r\n',
                    },
                    name: 'Ottoto Annex Black',
                    isEligibleForPolycarbonate: true,
                    frame: {
                        types: ['Full Frame'],
                        isNosePads: true,
                        mirror: '/mirror_frame/1/4086.png',
                        lensHeight: 36,
                        bridgeWidth: 18,
                        isSpringHinges: true,
                        templeLength: 150,
                        lensWidth: 56,
                        size: {
                            shortLabel: 'L',
                            label: 'Large',
                            id: 66,
                            position: 3,
                        },
                        materials: ['Metal'],
                        shapes: ['Rectangle'],
                        width: 140,
                        sgMirror: '/mirror_frame/1/4086_sg.png',
                        id: 3652,
                    },
                    supplierSku: 'FF303757-001',
                    attributeSetId: 26,
                    featured: [
                        {
                            featured: 4,
                            category_id: 199,
                        },
                        {
                            featured: 4,
                            category_id: 199,
                        },
                        {
                            featured: 6,
                            category_id: 390,
                        },
                        {
                            featured: 6,
                            category_id: 391,
                        },
                    ],
                    bestsellers: '343',
                    maxSaleQty: 2,
                    isSaleable: true,
                    weighted: [
                        {
                            category_id: 3,
                            position: 1,
                            weighted: 2323,
                        },
                        {
                            category_id: 5,
                            position: 1,
                            weighted: 4406,
                        },
                        {
                            category_id: 7,
                            position: 1,
                            weighted: 2323,
                        },
                        {
                            category_id: 18,
                            position: 1,
                            weighted: 4406,
                        },
                        {
                            category_id: 31,
                            position: 1,
                            weighted: 0,
                        },
                        {
                            category_id: 104,
                            position: 1,
                            weighted: 4406,
                        },
                        {
                            category_id: 114,
                            position: 1,
                            weighted: 2323,
                        },
                        {
                            category_id: 116,
                            position: 1,
                            weighted: 2323,
                        },
                        {
                            category_id: 127,
                            position: 1,
                            weighted: 0,
                        },
                        {
                            category_id: 165,
                            position: 1,
                            weighted: 5505,
                        },
                        {
                            category_id: 199,
                            position: 1,
                            weighted: 4215,
                        },
                        {
                            category_id: 254,
                            position: 1,
                            weighted: 4406,
                        },
                        {
                            category_id: 307,
                            position: 1,
                            weighted: 2323,
                        },
                        {
                            category_id: 312,
                            position: 1,
                            weighted: 2323,
                        },
                        {
                            category_id: 339,
                            position: 1,
                            weighted: 0,
                        },
                        {
                            category_id: 351,
                            position: 1,
                            weighted: 0,
                        },
                        {
                            category_id: 353,
                            position: 1,
                            weighted: 0,
                        },
                        {
                            category_id: 366,
                            position: 1,
                            weighted: 0,
                        },
                        {
                            category_id: 390,
                            position: 1,
                            weighted: 0,
                        },
                        {
                            category_id: 391,
                            position: 1,
                            weighted: 0,
                        },
                    ],
                    glassesType: [
                        {
                            id: 225,
                            label: 'Optical',
                            position: 0,
                        },
                        {
                            id: 227,
                            label: 'Rx.Sunglasses',
                            position: 0,
                        },
                        {
                            id: 226,
                            label: 'Sunglasses',
                            position: 0,
                        },
                    ],
                    visibility: {
                        label: 'Catalog, Search',
                        id: 4,
                        position: 4,
                    },
                    useLensPackage: true,
                    contactLensPerBox: 0,
                    parentId: 9674,
                    categoryId: [
                        3,
                        5,
                        7,
                        18,
                        31,
                        104,
                        114,
                        116,
                        127,
                        165,
                        199,
                        254,
                        307,
                        312,
                        339,
                        351,
                        353,
                        366,
                        390,
                        391,
                    ],
                    faceShape: [
                        {
                            label: 'Rectangle',
                            id: 43,
                            position: 1,
                        },
                    ],
                    manufacturer: 240,
                    manufacturerValue: 'Killine Group',
                    minPrice: 53.0,
                    maxPrice: 53,
                    frameMaterial: [
                        {
                            id: 1,
                            label: 'Metal',
                            position: 0,
                        },
                    ],
                    frameType: [
                        {
                            id: 95,
                            label: 'Full Frame',
                            position: 0,
                        },
                    ],
                    gender: [
                        {
                            id: 4,
                            label: 'Men',
                            position: 1,
                        },
                    ],
                    insurance: {
                        single_vision: 19.0,
                        reading: 19.0,
                        progressive: 39.0,
                        no_prescription: 19.0,
                        co_pay: 20.0,
                        bifocal: 39.0,
                        transition: 39.0,
                        frame: 19.0,
                    },
                    contactLensMaterialContent: '',
                    contactLensTypeText: '',
                    contactLensWaterPercentage: '',
                    contactLensPackageDetails: '',
                    upc: '',
                    eligibleForHto: true,
                    isSubscriptionAvailable: false,
                    extlab: {
                        id: 1,
                        name: 'Shamir',
                    },
                    badges: [
                        {
                            label: 'Clearance',
                            id: 131,
                            position: 5,
                        },
                    ],
                },
            ],
        },
        {
            id: 4852,
            url: 'ray-ban-rx5228.html',
            name: 'Ray-Ban RX5228',
            sku: 'ray-ban-5228-window',
            attributeSetId: 30,
            typeId: 'glasseswindow',
            brand: {
                image: '/brand/1/Ray-Ban_1_image.png',
                id: 36,
                label: 'Ray-Ban',
                imageCase: '/brand/1/Ray-Ban_0_case_image.png',
                popular: 100,
                url: '/ray-ban',
                imageHeight: 40,
                categoryId: 1,
            },
            children: [
                {
                    color: {
                        src: '/catalog_filter_color/1/19.jpg',
                        id: '19',
                        label: 'Black',
                    },
                    isEligibleForRx: true,
                    glassesTypeIds: [225, 227, 226],
                    description:
                        'The Ray-Ban 5228 is the slimmer take on the iconic wayframe. Crafted from premium acetate, its sleek arms, silver accents and rich hue continues to leave a mark now just as it did in the early 1950’s.',
                    finalPrice: 191.0,
                    videos: {
                        men: {
                            thumbnail: '4_44-p3640_5.gif',
                            isDefault: true,
                            genderId: 4,
                            url: 'https://player.vimeo.com/video/319279783',
                        },
                        women: {
                            thumbnail: '5_44-p3640_6.gif',
                            isDefault: false,
                            genderId: 5,
                            url: 'https://player.vimeo.com/video/314449079',
                        },
                    },
                    media: {
                        '360rotation': {
                            src: '/catalog_product_view_4257/1/443640_360.jpg',
                            qty: 20,
                            value_id: '1324',
                            entity_id: '4257',
                            first: 20,
                        },
                        side: {
                            file: '/4/4/44-p3640_s.jpg',
                            src: '/catalog_product/1/44-p3640_s.jpg',
                            value_id: 131908,
                            position: 3,
                            entity_id: 4257,
                        },
                        '180rotation': {
                            src: '/catalog_product_view_4257/1/44p3640_strip.jpg',
                            qty: 5,
                            value_id: '16586',
                            entity_id: '4257',
                            first: 3,
                        },
                        '180women': {
                            src: '/catalog_product_view_4257/1/443640_w.jpg',
                            qty: 5,
                            value_id: '29448',
                            entity_id: '4257',
                            first: 3,
                        },
                        '180men': {
                            src: '/catalog_product_view_4257/1/443640_m_1.jpg',
                            qty: 5,
                            value_id: '19293',
                            entity_id: '4257',
                            first: 3,
                        },
                        angle: {
                            file: '/4/4/44-p3640_u.jpg',
                            src: '/catalog_product/1/44-p3640_u.jpg',
                            value_id: 131909,
                            position: 1,
                            entity_id: 4257,
                        },
                        front: {
                            file: '/4/4/44-p3640_f.jpg',
                            src: '/catalog_product/1/44-p3640_f.jpg',
                            value_id: 131907,
                            position: 2,
                            entity_id: 4257,
                        },
                    },
                    type: 'eyeglasses',
                    templateId: 11,
                    isKids: false,
                    customProductBadge: [],
                    price: 191.0,
                    defaultTintSku: '',
                    id: 4257,
                    lensFeatures: [],
                    sku: '44-P3640',
                    stock: {
                        qty: 437,
                        status: 'in_stock',
                    },
                    relatedProductSku: '',
                    brand: {
                        image: '/brand/1/Ray-Ban_1_image.png',
                        id: 36,
                        label: 'Ray-Ban',
                        imageCase: '/brand/1/Ray-Ban_0_case_image.png',
                        popular: 100,
                        url: '/ray-ban',
                        imageHeight: 40,
                        categoryId: 1,
                    },
                    lensTypeIds: [7, 6, 10],
                    coupon: {
                        code: 'LENSES60',
                        price: 189.0,
                    },
                    isDsco: false,
                    genders: ['Men', 'Women'],
                    shortDescription:
                        'The Ray-Ban 5228 is the slimmer take on the iconic wayframe. Crafted from premium acetate, its sleek arms, silver accents and rich hue continues to leave a mark now just as it did in the early 1950’s.\r\n',
                    url: 'black-large/ray-ban-rx5228/44-p3640.html',
                    defaultDarknessSku: '',
                    wizardId: '14',
                    meta: {
                        disable_http_code: 404,
                        description:
                            'The Ray-Ban 5228 is the slimmer take on the iconic wayframe. Crafted from premium acetate, its sleek arms, silver accents and rich hue continues to leave a mark now just as it did in the early 1950’s.',
                        title: 'Ray-Ban 5228 Black Prescription Eyeglasses',
                        keyword:
                            'Glasses, Eyeglasses, Eyewear, Eyeglass, Eye glasses, Eye glass, Prescription glasses, Glasses frame, Eye wear, Bifocals, Eyeglass frame, Eyeglasses frames, Prescription eyeglasses, Buy glasses, Sunglasses\r\n',
                    },
                    name: 'Ray-Ban 5228 Black',
                    isEligibleForPolycarbonate: true,
                    frame: {
                        types: ['Full Frame'],
                        isNosePads: true,
                        mirror: '/mirror_frame/1/4257.png',
                        lensHeight: 37,
                        bridgeWidth: 17,
                        isSpringHinges: true,
                        templeLength: 140,
                        lensWidth: 53,
                        size: {
                            shortLabel: 'M',
                            label: 'Medium',
                            id: 67,
                            position: 2,
                        },
                        materials: ['Acetate', 'Plastic'],
                        shapes: ['Rectangle', 'Classic Wayframe'],
                        width: 138,
                        sgMirror: '',
                        id: 3824,
                    },
                    supplierSku: '0RX5228200053',
                    attributeSetId: 26,
                    featured: [
                        {
                            featured: 1,
                            category_id: 239,
                        },
                        {
                            featured: 2,
                            category_id: 199,
                        },
                        {
                            featured: 1,
                            category_id: 71,
                        },
                        {
                            featured: 2,
                            category_id: 254,
                        },
                        {
                            featured: 5,
                            category_id: 390,
                        },
                        {
                            featured: 2,
                            category_id: 199,
                        },
                        {
                            featured: 3,
                            category_id: 97,
                        },
                        {
                            featured: 2,
                            category_id: 104,
                        },
                        {
                            featured: 5,
                            category_id: 391,
                        },
                    ],
                    bestsellers: '221',
                    maxSaleQty: 2,
                    isSaleable: true,
                    weighted: [
                        {
                            category_id: 3,
                            position: 1,
                            weighted: 3450,
                        },
                        {
                            category_id: 5,
                            position: 1,
                            weighted: 3573,
                        },
                        {
                            category_id: 7,
                            position: 1,
                            weighted: 3450,
                        },
                        {
                            category_id: 17,
                            position: 1,
                            weighted: 3450,
                        },
                        {
                            category_id: 18,
                            position: 1,
                            weighted: 3573,
                        },
                        {
                            category_id: 48,
                            position: 1,
                            weighted: 9000,
                        },
                        {
                            category_id: 71,
                            position: 1,
                            weighted: 8889,
                        },
                        {
                            category_id: 97,
                            position: 1,
                            weighted: 3410,
                        },
                        {
                            category_id: 103,
                            position: 1,
                            weighted: 3573,
                        },
                        {
                            category_id: 104,
                            position: 1,
                            weighted: 3573,
                        },
                        {
                            category_id: 127,
                            position: 1,
                            weighted: 0,
                        },
                        {
                            category_id: 136,
                            position: 1,
                            weighted: 10000,
                        },
                        {
                            category_id: 199,
                            position: 1,
                            weighted: 3601,
                        },
                        {
                            category_id: 209,
                            position: 1,
                            weighted: 3628,
                        },
                        {
                            category_id: 221,
                            position: 1,
                            weighted: 10000,
                        },
                        {
                            category_id: 224,
                            position: 1,
                            weighted: 10000,
                        },
                        {
                            category_id: 225,
                            position: 1,
                            weighted: 10000,
                        },
                        {
                            category_id: 226,
                            position: 1,
                            weighted: 10000,
                        },
                        {
                            category_id: 235,
                            position: 1,
                            weighted: 3573,
                        },
                        {
                            category_id: 236,
                            position: 1,
                            weighted: 3573,
                        },
                        {
                            category_id: 239,
                            position: 1,
                            weighted: 8889,
                        },
                        {
                            category_id: 254,
                            position: 1,
                            weighted: 3573,
                        },
                        {
                            category_id: 286,
                            position: 1,
                            weighted: 9000,
                        },
                        {
                            category_id: 307,
                            position: 1,
                            weighted: 3450,
                        },
                        {
                            category_id: 310,
                            position: 1,
                            weighted: 3450,
                        },
                        {
                            category_id: 312,
                            position: 1,
                            weighted: 3450,
                        },
                        {
                            category_id: 353,
                            position: 1,
                            weighted: 0,
                        },
                        {
                            category_id: 390,
                            position: 1,
                            weighted: 0,
                        },
                        {
                            category_id: 391,
                            position: 1,
                            weighted: 0,
                        },
                        {
                            category_id: 403,
                            position: 1,
                            weighted: 0,
                        },
                    ],
                    glassesType: [
                        {
                            id: 225,
                            label: 'Optical',
                            position: 0,
                        },
                        {
                            id: 227,
                            label: 'Rx.Sunglasses',
                            position: 0,
                        },
                        {
                            id: 226,
                            label: 'Sunglasses',
                            position: 0,
                        },
                    ],
                    visibility: {
                        label: 'Catalog, Search',
                        id: 4,
                        position: 4,
                    },
                    useLensPackage: true,
                    contactLensPerBox: 0,
                    parentId: 4852,
                    categoryId: [
                        3,
                        5,
                        7,
                        17,
                        18,
                        48,
                        71,
                        97,
                        103,
                        104,
                        127,
                        136,
                        199,
                        209,
                        221,
                        224,
                        225,
                        226,
                        235,
                        236,
                        239,
                        254,
                        286,
                        307,
                        310,
                        312,
                        353,
                        390,
                        391,
                        403,
                    ],
                    faceShape: [
                        {
                            label: 'Rectangle',
                            id: 43,
                            position: 1,
                        },
                        {
                            label: 'Classic Wayframe',
                            id: 45,
                            position: 3,
                        },
                    ],
                    manufacturer: 196,
                    manufacturerValue: 'Luxottica USA',
                    minPrice: 191.0,
                    maxPrice: 191,
                    frameMaterial: [
                        {
                            id: 402,
                            label: 'Acetate',
                            position: 0,
                        },
                        {
                            id: 2,
                            label: 'Plastic',
                            position: 0,
                        },
                    ],
                    frameType: [
                        {
                            id: 95,
                            label: 'Full Frame',
                            position: 0,
                        },
                    ],
                    gender: [
                        {
                            id: 4,
                            label: 'Men',
                            position: 1,
                        },
                        {
                            id: 5,
                            label: 'Women',
                            position: 2,
                        },
                    ],
                    insurance: {
                        single_vision: 39.0,
                        reading: 39.0,
                        progressive: 59.0,
                        no_prescription: 39.0,
                        co_pay: 30.0,
                        bifocal: 59.0,
                        transition: 59.0,
                        frame: 39.0,
                    },
                    contactLensMaterialContent: '',
                    contactLensTypeText: '',
                    contactLensWaterPercentage: '',
                    contactLensPackageDetails: '',
                    upc: '805289445906',
                    isSubscriptionAvailable: false,
                    extlab: {
                        id: 9,
                        name: 'ATL',
                    },
                    badges: [
                        {
                            label: 'Premium Frames',
                            id: 127,
                            position: 11,
                        },
                    ],
                },
            ],
        },
        {
            id: 15711,
            url: 'elle.html',
            name: 'Muse Elle',
            sku: 'muse-elle-window',
            attributeSetId: 30,
            typeId: 'glasseswindow',
            brand: {
                id: 145,
                label: 'Muse',
                popular: 23,
                url: '/muse-eyewear',
                image: '/brand/1/Muse_0_image.png',
                imageHeight: 20,
                categoryId: 120,
            },
            children: [
                {
                    id: 15707,
                    url: 'black-medium/muse-elle/39-p9488.html',
                    name: 'Muse Elle Black',
                    sku: '39-P9488',
                    coupon: {
                        code: 'DEAL60',
                        price: 27.2,
                    },
                    brand: {
                        id: 145,
                        label: 'Muse',
                        popular: 23,
                        url: '/muse-eyewear',
                        image: '/brand/1/Muse_0_image.png',
                        imageHeight: 20,
                        categoryId: 120,
                    },
                    shortDescription:
                        'The Muse Elle is a modern rectangular frame with a subtle twist of retro. Crafted from high-grade acetate, it features a saddle bridge, elegant arms and stylish translucent colors.',
                    description:
                        'The Muse Elle is a modern rectangular frame with a subtle twist of retro. Crafted from high-grade acetate, it features a saddle bridge, elegant arms and stylish translucent colors.',
                    price: 68.0,
                    finalPrice: 68.0,
                    type: 'eyeglasses',
                    customProductBadge: [],
                    media: {
                        angle: {
                            entity_id: 15707,
                            src: '/catalog_product/1/9488_u.jpg',
                            value_id: 78218,
                            position: 1,
                            file: '/9/4/9488_u.jpg',
                        },
                        front: {
                            entity_id: 15707,
                            src: '/catalog_product/1/9488_f.jpg',
                            value_id: 78217,
                            position: 2,
                            file: '/9/4/9488_f.jpg',
                        },
                        side: {
                            entity_id: 15707,
                            src: '/catalog_product/1/9488_s.jpg',
                            value_id: 78216,
                            position: 3,
                            file: '/9/4/9488_s.jpg',
                        },
                        '180men': {
                            entity_id: '15707',
                            src: '/catalog_product_view_15707/1/399488_m.jpg',
                            qty: 5,
                            first: 3,
                            value_id: '28491',
                        },
                    },
                    videos: [],
                    genders: ['Men'],
                    stock: {
                        status: 'in_stock',
                        qty: 1997,
                    },
                    isDsco: false,
                    isKids: false,
                    defaultTintSku: '',
                    defaultDarknessSku: '',
                    relatedProductSku: '',
                    meta: {
                        disable_http_code: 404,
                        title: 'Muse Elle Black Prescription eyeglasses',
                        keyword:
                            'Glasses, Eyeglasses, Eyewear, Eyeglass, Eye glasses, Eye glass, Prescription glasses, Glasses frame, Eye wear, Bifocals, Eyeglass frame, Eyeglasses frames, Prescription eyeglasses, Buy glasses',
                        description:
                            'The Muse Elle is a modern rectangular frame with a subtle twist of retro. Crafted from high-grade acetate, it features a saddle bridge, elegant arms and stylish translucent colors.',
                    },
                    color: {
                        id: '19',
                        label: 'Black',
                        src: '/catalog_filter_color/1/19.jpg',
                    },
                    lensFeatures: [],
                    lensTypeIds: [7, 6, 10],
                    glassesTypeIds: [225, 227, 226],
                    frame: {
                        id: 11773,
                        size: {
                            label: 'Medium',
                            shortLabel: 'M',
                            id: 67,
                            position: 2,
                        },
                        materials: ['Acetate'],
                        shapes: ['Rectangle'],
                        types: ['Full Frame'],
                        isSpringHinges: false,
                        isNosePads: true,
                        width: 138,
                        lensWidth: 54,
                        lensHeight: 38,
                        bridgeWidth: 17,
                        templeLength: 145,
                        mirror: '/mirror_frame/1/15707.png',
                        sgMirror: '/mirror_frame/1/15707_sg.png',
                    },
                    isEligibleForRx: true,
                    isEligibleForPolycarbonate: true,
                    templateId: 1,
                    wizardId: '1',
                    supplierSku: 'FF083224-013',
                    attributeSetId: 26,
                    featured: [
                        {
                            category_id: 390,
                            featured: 12,
                        },
                        {
                            category_id: 391,
                            featured: 12,
                        },
                    ],
                    bestsellers: '330',
                    maxSaleQty: 2,
                    isSaleable: true,
                    weighted: [
                        {
                            category_id: 3,
                            weighted: 929,
                            position: 1,
                        },
                        {
                            category_id: 5,
                            weighted: 2758,
                            position: 1,
                        },
                        {
                            category_id: 7,
                            weighted: 929,
                            position: 1,
                        },
                        {
                            category_id: 18,
                            weighted: 2758,
                            position: 1,
                        },
                        {
                            category_id: 39,
                            weighted: 1527,
                            position: 1,
                        },
                        {
                            category_id: 42,
                            weighted: 1527,
                            position: 1,
                        },
                        {
                            category_id: 52,
                            weighted: 1527,
                            position: 1,
                        },
                        {
                            category_id: 54,
                            weighted: 1527,
                            position: 1,
                        },
                        {
                            category_id: 59,
                            weighted: 1527,
                            position: 1,
                        },
                        {
                            category_id: 80,
                            weighted: 1527,
                            position: 1,
                        },
                        {
                            category_id: 84,
                            weighted: 1527,
                            position: 1,
                        },
                        {
                            category_id: 97,
                            weighted: 3842,
                            position: 1,
                        },
                        {
                            category_id: 101,
                            weighted: 4566,
                            position: 1,
                        },
                        {
                            category_id: 104,
                            weighted: 2758,
                            position: 1,
                        },
                        {
                            category_id: 120,
                            weighted: 2758,
                            position: 1,
                        },
                        {
                            category_id: 127,
                            weighted: 0,
                            position: 1,
                        },
                        {
                            category_id: 199,
                            weighted: 2578,
                            position: 1,
                        },
                        {
                            category_id: 254,
                            weighted: 2758,
                            position: 1,
                        },
                        {
                            category_id: 307,
                            weighted: 929,
                            position: 1,
                        },
                        {
                            category_id: 310,
                            weighted: 929,
                            position: 1,
                        },
                        {
                            category_id: 312,
                            weighted: 929,
                            position: 1,
                        },
                        {
                            category_id: 351,
                            weighted: 0,
                            position: 1,
                        },
                        {
                            category_id: 353,
                            weighted: 0,
                            position: 1,
                        },
                        {
                            category_id: 366,
                            weighted: 0,
                            position: 1,
                        },
                        {
                            category_id: 390,
                            weighted: 0,
                            position: 1,
                        },
                        {
                            category_id: 391,
                            weighted: 0,
                            position: 1,
                        },
                        {
                            category_id: 403,
                            weighted: 0,
                            position: 1,
                        },
                    ],
                    glassesType: [
                        {
                            id: 225,
                            label: 'Optical',
                            position: 0,
                        },
                        {
                            id: 227,
                            label: 'Rx.Sunglasses',
                            position: 0,
                        },
                        {
                            id: 226,
                            label: 'Sunglasses',
                            position: 0,
                        },
                    ],
                    visibility: {
                        label: 'Catalog, Search',
                        id: 4,
                        position: 4,
                    },
                    useLensPackage: true,
                    contactLensPerBox: 0,
                    parentId: 15711,
                    categoryId: [
                        3,
                        5,
                        7,
                        18,
                        39,
                        42,
                        52,
                        54,
                        59,
                        80,
                        84,
                        97,
                        101,
                        104,
                        120,
                        127,
                        199,
                        254,
                        307,
                        310,
                        312,
                        351,
                        353,
                        366,
                        390,
                        391,
                        403,
                    ],
                    faceShape: [
                        {
                            label: 'Rectangle',
                            id: 43,
                            position: 1,
                        },
                    ],
                    manufacturer: 240,
                    manufacturerValue: 'Killine Group',
                    minPrice: 68.0,
                    maxPrice: 68,
                    frameMaterial: [
                        {
                            id: 402,
                            label: 'Acetate',
                            position: 0,
                        },
                    ],
                    frameType: [
                        {
                            id: 95,
                            label: 'Full Frame',
                            position: 0,
                        },
                    ],
                    gender: [
                        {
                            id: 4,
                            label: 'Men',
                            position: 1,
                        },
                    ],
                    insurance: {
                        single_vision: 19.0,
                        reading: 19.0,
                        progressive: 39.0,
                        bifocal: 39.0,
                        frame: 19.0,
                        no_prescription: 19.0,
                        transition: 39.0,
                        co_pay: 20.0,
                    },
                    contactLensMaterialContent: '',
                    contactLensTypeText: '',
                    contactLensWaterPercentage: '',
                    contactLensPackageDetails: '',
                    upc: '',
                    eligibleForHto: true,
                    isSubscriptionAvailable: false,
                    extlab: {
                        id: 1,
                        name: 'Shamir',
                    },
                    badges: [],
                },
            ],
        },
    ],
};
const getDetailParse = (notParsedItems) => {
    const res = notParsedItems.map((item) => {
        const product = item.children[0];
        return {
            images: {
                front: product.media.front,
                angle: product.media.angle,
            },
            frameSize: {
                shortLabel: product.frame.size.shortLabel,
                label: product.frame.size.label,
            },
            sku: product.sku,
            type: product.type,
            url: product.url,
            name: product.name,
            price: product.price,
            finalPrice: product.finalPrice,
            isSaleable: product.isSaleable,
            frameIsMultifocal: product.lensTypeIds.includes(MULTIFOCAL_LENS_TYPE_ID),
            isLensTypeActive: product.isEligibleForRx,
            materials: product.frame.materials,
            shapes: product.frame.shapes,
            types: product.frame.types,
            productId: product.id,
            frameSizes: `${product.frame.lensWidth}–${product.frame.bridgeWidth}–${product.frame.templeLength}`,
        };
    });
    console.dir(res.map(item => item.images), 6);
    return res;
};
getDetailParse(detailedResponse.items)
// fs.writeFile('result.js', getDetailParse(detailedResponse.items), function(error){
//     if(error) throw error; // ошибка чтения файла, если есть
//     console.log('Данные успешно записаны записать файл');
// });